basePath: /apis/api.kubetail.com/v1
info:
  contact: {}
  title: Kubetail Cluster API
  version: "1.0"
paths:
  /api.kubetail.com/v1/dummy:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: returns dummy response
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Dummy response xxx
swagger: "2.0"
