// This code was autogenerated from proto/agent.proto, do not edit.
package api

import (
	"context"
	"log"
	"time"

	"google.golang.org/protobuf/proto"
	"github.com/nats-io/nats.go"
	"github.com/nats-rpc/nrpc"
)

// ServerServiceServer is the interface that providers of the service
// ServerService should implement.
type ServerServiceServer interface {
	GetServerName(ctx context.Context, req *ServerRequest) (*ServerResponse, error)
}

// ServerServiceHandler provides a NATS subscription handler that can serve a
// subscription using a given ServerServiceServer implementation.
type ServerServiceHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  ServerServiceServer

	encodings []string
}

func NewServerServiceHandler(ctx context.Context, nc nrpc.NatsConn, s ServerServiceServer) *ServerServiceHandler {
	return &ServerServiceHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,

		encodings: []string{"protobuf"},
	}
}

func NewServerServiceConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s ServerServiceServer) *ServerServiceHandler {
	return &ServerServiceHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

// SetEncodings sets the output encodings when using a '*Publish' function
func (h *ServerServiceHandler) SetEncodings(encodings []string) {
	h.encodings = encodings
}

func (h *ServerServiceHandler) Subject() string {
	return "ServerService.*.>"
}

func (h *ServerServiceHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, svcParams, name, tail, err := nrpc.ParseSubject(
		"", 0, "ServerService", 1, msg.Subject)
	if err != nil {
		log.Printf("ServerServiceHanlder: ServerService subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail
	request.SetServiceParam("nodeName", svcParams[0])

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "GetServerName":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("GetServerNameHanlder: GetServerName subject parsing failed: %v", err)
			break
		}
		var req ServerRequest
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("GetServerNameHandler: GetServerName request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.GetServerName(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	default:
		log.Printf("ServerServiceHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("ServerServiceHandler: ServerService handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type ServerServiceClient struct {
	nc      nrpc.NatsConn
	Subject string
	SvcParamnodeName string
	Encoding string
	Timeout time.Duration
}

func NewServerServiceClient(nc nrpc.NatsConn, svcParamnodeName string) *ServerServiceClient {
	return &ServerServiceClient{
		nc:      nc,
		Subject: "ServerService",
		SvcParamnodeName: svcParamnodeName,
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *ServerServiceClient) GetServerName(req *ServerRequest) (*ServerResponse, error) {

	subject := c.Subject + "." + c.SvcParamnodeName + "." + "GetServerName"

	// call
	var resp = ServerResponse{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	ServerService *ServerServiceClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
	}
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.ServerService != nil {
		c.ServerService.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.ServerService != nil {
		c.ServerService.Timeout = t
	}
}

func (c *Client) SetServerServiceParams(
	nodeName string,
) {
	c.ServerService = NewServerServiceClient(
		c.nc,
		nodeName,
	)
	c.ServerService.Encoding = c.defaultEncoding
	c.ServerService.Timeout = c.defaultTimeout
}

func (c *Client) NewServerService(
	nodeName string,
) *ServerServiceClient {
	client := NewServerServiceClient(
		c.nc,
		nodeName,
	)
	client.Encoding = c.defaultEncoding
	client.Timeout = c.defaultTimeout
	return client
}