package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"time"
)

// SayHi is the resolver for the sayHi field.
func (r *queryResolver) SayHi(ctx context.Context) (string, error) {
	return "hi", nil
}

// TestSub is the resolver for the testSub field.
func (r *subscriptionResolver) TestSub(ctx context.Context) (<-chan string, error) {
	outCh := make(chan string)

	go func() {
		ticker := time.NewTicker(5 * time.Second)

	Loop:
		for {
			select {
			case <-ctx.Done():
				break Loop
			case <-ticker.C:
				outCh <- time.Now().Format(time.RFC3339Nano)
			}
		}

		ticker.Stop()
		close(outCh)
	}()

	return outCh, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
