// This code was autogenerated from agent.proto, do not edit.
package agentpb

import (
	"context"
	"log"
	"time"

	"google.golang.org/protobuf/proto"
	"github.com/nats-io/nats.go"
	"github.com/nats-rpc/nrpc"
)

// PodLogMetadataServer is the interface that providers of the service
// PodLogMetadata should implement.
type PodLogMetadataServer interface {
	FileInfoGet(ctx context.Context, req *FileInfoRequest) (*FileInfoResponse, error)
	FileInfoList(ctx context.Context, req *FileInfoListRequest) (*FileInfoListResponse, error)
	FileInfoWatch(ctx context.Context, req *FileInfoRequest, pushRep func(*FileInfoResponse)) (error)
}

// PodLogMetadataHandler provides a NATS subscription handler that can serve a
// subscription using a given PodLogMetadataServer implementation.
type PodLogMetadataHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  PodLogMetadataServer

	encodings []string
}

func NewPodLogMetadataHandler(ctx context.Context, nc nrpc.NatsConn, s PodLogMetadataServer) *PodLogMetadataHandler {
	return &PodLogMetadataHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,

		encodings: []string{"protobuf"},
	}
}

func NewPodLogMetadataConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s PodLogMetadataServer) *PodLogMetadataHandler {
	return &PodLogMetadataHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

// SetEncodings sets the output encodings when using a '*Publish' function
func (h *PodLogMetadataHandler) SetEncodings(encodings []string) {
	h.encodings = encodings
}

func (h *PodLogMetadataHandler) Subject() string {
	return "PodLogMetadata.*.>"
}

func (h *PodLogMetadataHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, svcParams, name, tail, err := nrpc.ParseSubject(
		"", 0, "PodLogMetadata", 1, msg.Subject)
	if err != nil {
		log.Printf("PodLogMetadataHanlder: PodLogMetadata subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail
	request.SetServiceParam("nodeName", svcParams[0])

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "FileInfoGet":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("FileInfoGetHanlder: FileInfoGet subject parsing failed: %v", err)
			break
		}
		var req FileInfoRequest
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("FileInfoGetHandler: FileInfoGet request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.FileInfoGet(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	case "FileInfoList":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("FileInfoListHanlder: FileInfoList subject parsing failed: %v", err)
			break
		}
		var req FileInfoListRequest
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("FileInfoListHandler: FileInfoList request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.FileInfoList(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	case "FileInfoWatch":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("FileInfoWatchHanlder: FileInfoWatch subject parsing failed: %v", err)
			break
		}
		var req FileInfoRequest
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("FileInfoWatchHandler: FileInfoWatch request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.EnableStreamedReply()
			request.Handler = func(ctx context.Context)(proto.Message, error){
				err := h.server.FileInfoWatch(ctx, &req, func(rep *FileInfoResponse){
					request.SendStreamReply(rep)
				})
				return nil, err
			}
		}
	default:
		log.Printf("PodLogMetadataHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("PodLogMetadataHandler: PodLogMetadata handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type PodLogMetadataClient struct {
	nc      nrpc.NatsConn
	Subject string
	SvcParamnodeName string
	Encoding string
	Timeout time.Duration
}

func NewPodLogMetadataClient(nc nrpc.NatsConn, svcParamnodeName string) *PodLogMetadataClient {
	return &PodLogMetadataClient{
		nc:      nc,
		Subject: "PodLogMetadata",
		SvcParamnodeName: svcParamnodeName,
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *PodLogMetadataClient) FileInfoGet(req *FileInfoRequest) (*FileInfoResponse, error) {

	subject := c.Subject + "." + c.SvcParamnodeName + "." + "FileInfoGet"

	// call
	var resp = FileInfoResponse{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *PodLogMetadataClient) FileInfoList(req *FileInfoListRequest) (*FileInfoListResponse, error) {

	subject := c.Subject + "." + c.SvcParamnodeName + "." + "FileInfoList"

	// call
	var resp = FileInfoListResponse{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *PodLogMetadataClient) FileInfoListPoll(req *FileInfoListRequest,maxreplies int, cb func (*FileInfoListResponse) error,
) (error) {

	subject := c.Subject + "." + c.SvcParamnodeName + "." + "FileInfoList"

	var resp FileInfoListResponse

	err := nrpc.Poll(req, &resp, c.nc, subject, c.Encoding, c.Timeout, maxreplies,
		func() error {
			return cb(&resp)
		},
	)
	if err != nil {
		return err
	}

	return nil
}

func (c *PodLogMetadataClient) FileInfoWatch(
	ctx context.Context,
	req *FileInfoRequest,
	cb func (context.Context, *FileInfoResponse),
) error {
	subject := c.Subject + "." + c.SvcParamnodeName + "." + "FileInfoWatch"

	sub, err := nrpc.StreamCall(ctx, c.nc, subject, req, c.Encoding, c.Timeout)
	if err != nil {
		return err
	}

	var res FileInfoResponse
	for {
		err = sub.Next(&res)
		if err != nil {
			break
		}
		cb(ctx, &res)
	}
	if err == nrpc.ErrEOS {
		err = nil
	}
	return err
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	PodLogMetadata *PodLogMetadataClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
	}
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.PodLogMetadata != nil {
		c.PodLogMetadata.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.PodLogMetadata != nil {
		c.PodLogMetadata.Timeout = t
	}
}

func (c *Client) SetPodLogMetadataParams(
	nodeName string,
) {
	c.PodLogMetadata = NewPodLogMetadataClient(
		c.nc,
		nodeName,
	)
	c.PodLogMetadata.Encoding = c.defaultEncoding
	c.PodLogMetadata.Timeout = c.defaultTimeout
}

func (c *Client) NewPodLogMetadata(
	nodeName string,
) *PodLogMetadataClient {
	client := NewPodLogMetadataClient(
		c.nc,
		nodeName,
	)
	client.Encoding = c.defaultEncoding
	client.Timeout = c.defaultTimeout
	return client
}