// Copyright 2024 Andres Morey
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	LogMetadata_FileInfoList_FullMethodName  = "/agentpb.LogMetadata/FileInfoList"
	LogMetadata_FileInfoWatch_FullMethodName = "/agentpb.LogMetadata/FileInfoWatch"
)

// LogMetadataClient is the client API for LogMetadata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogMetadataClient interface {
	FileInfoList(ctx context.Context, in *FileInfoListRequest, opts ...grpc.CallOption) (*FileInfoListResponse, error)
	FileInfoWatch(ctx context.Context, in *FileInfoWatchRequest, opts ...grpc.CallOption) (LogMetadata_FileInfoWatchClient, error)
}

type logMetadataClient struct {
	cc grpc.ClientConnInterface
}

func NewLogMetadataClient(cc grpc.ClientConnInterface) LogMetadataClient {
	return &logMetadataClient{cc}
}

func (c *logMetadataClient) FileInfoList(ctx context.Context, in *FileInfoListRequest, opts ...grpc.CallOption) (*FileInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileInfoListResponse)
	err := c.cc.Invoke(ctx, LogMetadata_FileInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logMetadataClient) FileInfoWatch(ctx context.Context, in *FileInfoWatchRequest, opts ...grpc.CallOption) (LogMetadata_FileInfoWatchClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogMetadata_ServiceDesc.Streams[0], LogMetadata_FileInfoWatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &logMetadataFileInfoWatchClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LogMetadata_FileInfoWatchClient interface {
	Recv() (*FileInfoWatchEvent, error)
	grpc.ClientStream
}

type logMetadataFileInfoWatchClient struct {
	grpc.ClientStream
}

func (x *logMetadataFileInfoWatchClient) Recv() (*FileInfoWatchEvent, error) {
	m := new(FileInfoWatchEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogMetadataServer is the server API for LogMetadata service.
// All implementations must embed UnimplementedLogMetadataServer
// for forward compatibility
type LogMetadataServer interface {
	FileInfoList(context.Context, *FileInfoListRequest) (*FileInfoListResponse, error)
	FileInfoWatch(*FileInfoWatchRequest, LogMetadata_FileInfoWatchServer) error
	mustEmbedUnimplementedLogMetadataServer()
}

// UnimplementedLogMetadataServer must be embedded to have forward compatible implementations.
type UnimplementedLogMetadataServer struct {
}

func (UnimplementedLogMetadataServer) FileInfoList(context.Context, *FileInfoListRequest) (*FileInfoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileInfoList not implemented")
}
func (UnimplementedLogMetadataServer) FileInfoWatch(*FileInfoWatchRequest, LogMetadata_FileInfoWatchServer) error {
	return status.Errorf(codes.Unimplemented, "method FileInfoWatch not implemented")
}
func (UnimplementedLogMetadataServer) mustEmbedUnimplementedLogMetadataServer() {}

// UnsafeLogMetadataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogMetadataServer will
// result in compilation errors.
type UnsafeLogMetadataServer interface {
	mustEmbedUnimplementedLogMetadataServer()
}

func RegisterLogMetadataServer(s grpc.ServiceRegistrar, srv LogMetadataServer) {
	s.RegisterService(&LogMetadata_ServiceDesc, srv)
}

func _LogMetadata_FileInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogMetadataServer).FileInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogMetadata_FileInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogMetadataServer).FileInfoList(ctx, req.(*FileInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogMetadata_FileInfoWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileInfoWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogMetadataServer).FileInfoWatch(m, &logMetadataFileInfoWatchServer{ServerStream: stream})
}

type LogMetadata_FileInfoWatchServer interface {
	Send(*FileInfoWatchEvent) error
	grpc.ServerStream
}

type logMetadataFileInfoWatchServer struct {
	grpc.ServerStream
}

func (x *logMetadataFileInfoWatchServer) Send(m *FileInfoWatchEvent) error {
	return x.ServerStream.SendMsg(m)
}

// LogMetadata_ServiceDesc is the grpc.ServiceDesc for LogMetadata service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogMetadata_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentpb.LogMetadata",
	HandlerType: (*LogMetadataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileInfoList",
			Handler:    _LogMetadata_FileInfoList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileInfoWatch",
			Handler:       _LogMetadata_FileInfoWatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
