// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: proto/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PodLogMetadata_FileInfoGet_FullMethodName   = "/agentpb.PodLogMetadata/FileInfoGet"
	PodLogMetadata_FileInfoWatch_FullMethodName = "/agentpb.PodLogMetadata/FileInfoWatch"
)

// PodLogMetadataClient is the client API for PodLogMetadata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodLogMetadataClient interface {
	FileInfoGet(ctx context.Context, in *FileInfoRequest, opts ...grpc.CallOption) (*FileInfoResponse, error)
	FileInfoWatch(ctx context.Context, in *FileInfoRequest, opts ...grpc.CallOption) (PodLogMetadata_FileInfoWatchClient, error)
}

type podLogMetadataClient struct {
	cc grpc.ClientConnInterface
}

func NewPodLogMetadataClient(cc grpc.ClientConnInterface) PodLogMetadataClient {
	return &podLogMetadataClient{cc}
}

func (c *podLogMetadataClient) FileInfoGet(ctx context.Context, in *FileInfoRequest, opts ...grpc.CallOption) (*FileInfoResponse, error) {
	out := new(FileInfoResponse)
	err := c.cc.Invoke(ctx, PodLogMetadata_FileInfoGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podLogMetadataClient) FileInfoWatch(ctx context.Context, in *FileInfoRequest, opts ...grpc.CallOption) (PodLogMetadata_FileInfoWatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &PodLogMetadata_ServiceDesc.Streams[0], PodLogMetadata_FileInfoWatch_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &podLogMetadataFileInfoWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PodLogMetadata_FileInfoWatchClient interface {
	Recv() (*FileInfoResponse, error)
	grpc.ClientStream
}

type podLogMetadataFileInfoWatchClient struct {
	grpc.ClientStream
}

func (x *podLogMetadataFileInfoWatchClient) Recv() (*FileInfoResponse, error) {
	m := new(FileInfoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PodLogMetadataServer is the server API for PodLogMetadata service.
// All implementations must embed UnimplementedPodLogMetadataServer
// for forward compatibility
type PodLogMetadataServer interface {
	FileInfoGet(context.Context, *FileInfoRequest) (*FileInfoResponse, error)
	FileInfoWatch(*FileInfoRequest, PodLogMetadata_FileInfoWatchServer) error
	mustEmbedUnimplementedPodLogMetadataServer()
}

// UnimplementedPodLogMetadataServer must be embedded to have forward compatible implementations.
type UnimplementedPodLogMetadataServer struct {
}

func (UnimplementedPodLogMetadataServer) FileInfoGet(context.Context, *FileInfoRequest) (*FileInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileInfoGet not implemented")
}
func (UnimplementedPodLogMetadataServer) FileInfoWatch(*FileInfoRequest, PodLogMetadata_FileInfoWatchServer) error {
	return status.Errorf(codes.Unimplemented, "method FileInfoWatch not implemented")
}
func (UnimplementedPodLogMetadataServer) mustEmbedUnimplementedPodLogMetadataServer() {}

// UnsafePodLogMetadataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodLogMetadataServer will
// result in compilation errors.
type UnsafePodLogMetadataServer interface {
	mustEmbedUnimplementedPodLogMetadataServer()
}

func RegisterPodLogMetadataServer(s grpc.ServiceRegistrar, srv PodLogMetadataServer) {
	s.RegisterService(&PodLogMetadata_ServiceDesc, srv)
}

func _PodLogMetadata_FileInfoGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodLogMetadataServer).FileInfoGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodLogMetadata_FileInfoGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodLogMetadataServer).FileInfoGet(ctx, req.(*FileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodLogMetadata_FileInfoWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileInfoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PodLogMetadataServer).FileInfoWatch(m, &podLogMetadataFileInfoWatchServer{stream})
}

type PodLogMetadata_FileInfoWatchServer interface {
	Send(*FileInfoResponse) error
	grpc.ServerStream
}

type podLogMetadataFileInfoWatchServer struct {
	grpc.ServerStream
}

func (x *podLogMetadataFileInfoWatchServer) Send(m *FileInfoResponse) error {
	return x.ServerStream.SendMsg(m)
}

// PodLogMetadata_ServiceDesc is the grpc.ServiceDesc for PodLogMetadata service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodLogMetadata_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentpb.PodLogMetadata",
	HandlerType: (*PodLogMetadataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileInfoGet",
			Handler:    _PodLogMetadata_FileInfoGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileInfoWatch",
			Handler:       _PodLogMetadata_FileInfoWatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
