// This code was autogenerated from agent.proto, do not edit.
package agentpb

import (
	"context"
	"log"
	"time"

	"google.golang.org/protobuf/proto"
	"github.com/nats-io/nats.go"
	"github.com/nats-rpc/nrpc"
)

// LogMetadataServer is the interface that providers of the service
// LogMetadata should implement.
type LogMetadataServer interface {
	FileInfoList(ctx context.Context, req *FileInfoListRequest) (*FileInfoListResponse, error)
}

// LogMetadataHandler provides a NATS subscription handler that can serve a
// subscription using a given LogMetadataServer implementation.
type LogMetadataHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  LogMetadataServer

	encodings []string
}

func NewLogMetadataHandler(ctx context.Context, nc nrpc.NatsConn, s LogMetadataServer) *LogMetadataHandler {
	return &LogMetadataHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,

		encodings: []string{"protobuf"},
	}
}

func NewLogMetadataConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s LogMetadataServer) *LogMetadataHandler {
	return &LogMetadataHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

// SetEncodings sets the output encodings when using a '*Publish' function
func (h *LogMetadataHandler) SetEncodings(encodings []string) {
	h.encodings = encodings
}

func (h *LogMetadataHandler) Subject() string {
	return "LogMetadata.*.>"
}

func (h *LogMetadataHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, svcParams, name, tail, err := nrpc.ParseSubject(
		"", 0, "LogMetadata", 1, msg.Subject)
	if err != nil {
		log.Printf("LogMetadataHanlder: LogMetadata subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail
	request.SetServiceParam("nodeName", svcParams[0])

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "FileInfoList":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("FileInfoListHanlder: FileInfoList subject parsing failed: %v", err)
			break
		}
		var req FileInfoListRequest
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("FileInfoListHandler: FileInfoList request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.FileInfoList(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	default:
		log.Printf("LogMetadataHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("LogMetadataHandler: LogMetadata handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type LogMetadataClient struct {
	nc      nrpc.NatsConn
	Subject string
	SvcParamnodeName string
	Encoding string
	Timeout time.Duration
}

func NewLogMetadataClient(nc nrpc.NatsConn, svcParamnodeName string) *LogMetadataClient {
	return &LogMetadataClient{
		nc:      nc,
		Subject: "LogMetadata",
		SvcParamnodeName: svcParamnodeName,
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *LogMetadataClient) FileInfoList(req *FileInfoListRequest) (*FileInfoListResponse, error) {

	subject := c.Subject + "." + c.SvcParamnodeName + "." + "FileInfoList"

	// call
	var resp = FileInfoListResponse{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *LogMetadataClient) FileInfoListPoll(req *FileInfoListRequest,maxreplies int, cb func (*FileInfoListResponse) error,
) (error) {

	subject := c.Subject + "." + c.SvcParamnodeName + "." + "FileInfoList"

	var resp FileInfoListResponse

	err := nrpc.Poll(req, &resp, c.nc, subject, c.Encoding, c.Timeout, maxreplies,
		func() error {
			return cb(&resp)
		},
	)
	if err != nil {
		return err
	}

	return nil
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	LogMetadata *LogMetadataClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
	}
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.LogMetadata != nil {
		c.LogMetadata.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.LogMetadata != nil {
		c.LogMetadata.Timeout = t
	}
}

func (c *Client) SetLogMetadataParams(
	nodeName string,
) {
	c.LogMetadata = NewLogMetadataClient(
		c.nc,
		nodeName,
	)
	c.LogMetadata.Encoding = c.defaultEncoding
	c.LogMetadata.Timeout = c.defaultTimeout
}

func (c *Client) NewLogMetadata(
	nodeName string,
) *LogMetadataClient {
	client := NewLogMetadataClient(
		c.nc,
		nodeName,
	)
	client.Encoding = c.defaultEncoding
	client.Timeout = c.defaultTimeout
	return client
}