name: publish-guru

permissions:
  contents: read

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        required: true
        type: string
      dry_run:
        description: "Dry run"
        required: false
        type: boolean
        default: true

jobs:
  config:
    name: Configure workflow
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.config.outputs.version }}
      dry_run: ${{ steps.config.outputs.dry_run }}
    steps:
      - id: config
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "dry_run=${{ github.event.inputs.dry_run }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/cli/v}" >> $GITHUB_OUTPUT
            echo "dry_run=false" >> $GITHUB_OUTPUT
          fi

  update-kubetail:
    name: Update `kubetail`
    needs: [config]
    runs-on: ubuntu-24.04
    env:
      ARCHIVE_NAME: "kubetail-cli.orig.tar.xz"
    steps:
      - name: Download source bundle
        uses: robinraju/release-downloader@v1.12
        with:
          repository: kubetail-org/kubetail
          tag: ${{ format('cli/v{0}', needs.config.outputs.version) }}
          fileName: ${{ env.ARCHIVE_NAME }}
          out-file-path: "downloads"

      - name: Extract metadata
        id: meta
        working-directory: ./downloads
        run: |
          SIZE=$(stat --format '%s' "$ARCHIVE_NAME")
          BLAKE2B=$(b2sum "$ARCHIVE_NAME" | awk '{print $1}')
          SHA512=$(sha512sum "$ARCHIVE_NAME" | awk '{print $1}')

          echo "size=$SIZE" >> "$GITHUB_OUTPUT"
          echo "blake2b=$BLAKE2B" >> "$GITHUB_OUTPUT"
          echo "sha512=$SHA512" >> "$GITHUB_OUTPUT"

      - name: Load GURU SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.GENTOO_SSH_PRIVATE_KEY }}

      - name: Checkout GURU repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GENTOO_SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

          git clone --depth 1 git@git.gentoo.org:repo/proj/guru.git

      - name: Update Manifest
        working-directory: guru/dev-util/kubetail
        run: |
          echo "DIST $ARCHIVE_NAME ${{ steps.meta.outputs.size }} BLAKE2B ${{ steps.meta.outputs.blake2b }} SHA512 ${{ steps.meta.outputs.sha512 }}" >> Manifest
          cat Manifest
