name: release-cli

permissions:
  contents: write

on:
  push:
    tags:
      - "cli/v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
      dry_run:
        description: "Dry run"
        required: false
        type: boolean
        default: true

jobs:
  config:
    name: Configure workflow
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.config.outputs.version }}
      dry_run: ${{ steps.config.outputs.dry_run }}
    steps:
      - id: config
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "dry_run=${{ github.event.inputs.dry_run }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/cli/v}" >> $GITHUB_OUTPUT
            echo "dry_run=false" >> $GITHUB_OUTPUT
          fi

  prepare:
    name: Prepare source
    needs: config
    runs-on: ubuntu-24.04
    steps:
      - uses: ./.github/actions/setup-environment
        with:
          setup-node: "true"
          setup-go: "true"
      - uses: actions/checkout@v5
        with:
          ref: refs/tags/cli/v${{ needs.config.outputs.version }}
      - name: Build frontend
        working-directory: dashboard-ui
        run: |
          pnpm install
          pnpm build
      - name: Vendor backend
        run: |
          rm -rf modules/dashboard/website
          mv dashboard-ui/dist modules/dashboard/website
          cd modules/cli
          go mod vendor
      - name: Clean up source directory
        run: |
          rm -rf .git
          rm -rf dashboard-ui/node_modules
          git reset --hard
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: source
          path: .

  build:
    name: Build binaries
    needs: [config, prepare]
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-latest
          - macos-13
          - windows-latest
          - windows-11-arm
        include:
          - runner: ubuntu-24.04
            GOOS: linux
            GOARCH: amd64
          - runner: ubuntu-24.04-arm
            GOOS: linux
            GOARCH: arm64
          - runner: macos-latest
            GOOS: darwin
            GOARCH: arm64
          - runner: macos-13
            GOOS: darwin
            GOARCH: amd64
          - runner: windows-latest
            GOOS: windows
            GOARCH: amd64
          - runner: windows-11-arm
            GOOS: windows
            GOARCH: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: ./.github/actions/setup-environment
        with:
          setup-go: "true"
      - name: Download source
        uses: actions/download-artifact@v6
        with:
          name: source
          path: .
      - name: Build binary
        working-directory: modules/cli
        env:
          GOWORK: off
          CGO_ENABLED: 0
          LDFLAGS: "-s -w -X 'github.com/kubetail-org/kubetail/modules/cli/cmd.version=${{ needs.config.outputs.version }}'"
        run: |
          go build -ldflags=$(LDFLAGS) -o ../../bin/kubetail .
      - name: Append os/arch to binary file name
        run: mv bin/kubetail bin/kubetail-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          path: bin/*
          name: assets-${{ matrix.GOOS }}-${{ matrix.GOARCH }}

  sign:
    name: Create windows zip and sign binaries
    needs: [config, build]
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          name: assets-windows-${{ matrix.arch }}
          path: files
      - name: Create zip archive
        shell: pwsh
        run: |
          $file = "kubetail-windows-${{ matrix.arch }}"
          Copy-Item -Path $file -Destination kubetail.exe
          Compress-Archive -Path kubetail.exe -DestinationPath "${file}.zip"
          Remove-Item kubetail.exe
      - id: upload-artifact
        name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          path: files
          name: assets-windows-${{ matrix.arch }}
          overwrite: true
      - name: Sign Windows Binaries
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: "${{ secrets.SIGNPATH_API_TOKEN }}"
          organization-id: "${{ secrets.SIGNPATH_ORGANIZATION_ID }}"
          project-slug: "kubetail"
          signing-policy-slug: "release-signing"
          github-artifact-id: "${{ steps.upload-artifact.outputs.artifact-id }}"
          wait-for-completion: true
          output-artifact-directory: files
          parameters: |
            os: ${{ toJSON('windows') }}
            arch: ${{ toJSON(matrix.arch) }}
            version: ${{ toJSON(needs.config.outputs.version) }}
      - name: Upload signed artifacts
        uses: actions/upload-artifact@v5
        with:
          path: files
          name: assets-windows-${{ matrix.arch }}
          overwrite: true

  package-tarball:
    name: Create gzipped tarballs
    needs: sign
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        os:
          - darwin
          - linux
          - windows
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            LICENSE
          sparse-checkout-cone-mode: false
          path: repo
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          name: assets-${{ matrix.os }}-${{ matrix.arch }}
          path: files
      - name: Create gzipped tarball
        env:
          REPO_PATH: repo
          FILES_PATH: files
          BIN_NAME: kubetail-${{ matrix.os }}-${{ matrix.arch }}
        run: |
          TEMP_DIR="$(mktemp -d)"

          TARGET_NAME="kubetail"
          if [ "${{ matrix.os }}" = "windows" ]; then
            TARGET_NAME="kubetail.exe"
          fi

          chmod +x "${FILES_PATH}/${BIN_NAME}"
          mv "${FILES_PATH}/${BIN_NAME}" "${TEMP_DIR}/${TARGET_NAME}"
          cp "${REPO_PATH}/LICENSE" "${TEMP_DIR}/LICENSE"
          tar -C "${TEMP_DIR}" -czf "${FILES_PATH}/${BIN_NAME}.tar.gz" "${TARGET_NAME}" LICENSE
          rm -rf "${TEMP_DIR}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: assets-${{ matrix.os }}-${{ matrix.arch }}-tgz
          path: files

  release:
    name: Create GitHub release
    needs: [config, package-tarball]
    runs-on: ubuntu-24.04
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v6
        with:
          pattern: assets-*
          path: assets
          merge-multiple: true
      - name: Download source
        uses: actions/download-artifact@v6
        with:
          name: source
          path: kubetail-cli
      - name: Create source tarball
        run: |
          tar -cJf assets/kubetail-cli.orig.tar.xz kubetail-cli
      - name: Generate SHA-256 checksums
        working-directory: ./assets
        run: |
          sha256sum * > SHA245SUMS
      - name: Create release
        uses: softprops/action-gh-release@v2.3.2
        if: ${{ needs.config.outputs.dry_run != 'true' }}
        with:
          files: assets/*
          draft: true
      - name: Debug
        if: ${{ needs.config.outputs.dry_run == 'true' }}
        run: |
          ls -lah assets/*
          cat assets/SHA256SUMS
